# Generated by Django 3.1.6 on 2021-02-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_skip',
            new_name='votes_to_skip',
        ),
    ]
